### ISSUE TITLE
Add version number

### ISSUE THREAD

**Issue by hatched** [canonical/multipass.run#55]
It would be nice if the website had the current version listed somewhere. Maybe in the "Install" section.

**Comment by nottrobin** [comment]
@hatched you mean the version of multipass?

It turns out that we've now been coerced into adding it here: https://staging.multipass.run/static/latest-release.json. But I hope that's only a temporary solution.

I'd rather try to find some sort of solution that didn't require us to manually keep it up-to-date.

**Comment by hatched** [comment]
Yeah the version of multipass. There doesn't appear to be any way to find out what the current version is on the website anywhere.

**Comment by g1964j** [comment]
Quel numéro  vous dite suffit pour le moment un peu de repit pour voir plus clair des action passe de qui
